---
- name: Update OS to latest
  package:
    name: '*'
    state: latest

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernelModules }}"

- name: Include OS specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "tasks/tasks-{{ ansible_facts['os_family'] }}.yml"

- name: Start and enable CRI-O
  systemd:
    name: crio
    state: started
    enabled: true
