---
- name: Enable CRI-O repository
  yum_repository:
    name: crio-o
    description: CRI-O Repo
    baseurl: "{{ crioRepo }}"
    gpgcheck: no

- name: Install CRI-O
  yum:
    name: cri-o
    state: latest
    update_cache: true
